name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Run bench
        run: cargo bench
      - name: Save benchmark result
        uses: actions/upload-artifact@v2
        with:
          name: benchmark.svg
          path: "$GITHUB_WORKSPACE/target/criterion/fuzzy search algorithm benchmarks/report/violin.svg"
